name: Docker

on:
    push:
       branches:
          - main
    workflow_dispatch:
    schedule:
      - cron: '0 0 1 * *' # Every first day of the month

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          file: ./Dockerfile
          tags:  |
            ghcr.io/craftmania-cz/docker-java21:${{ github.run_id }}
            ghcr.io/craftmania-cz/docker-java21:latest